### ISSUE TITLE
Enkele organisaties hebben een uri die niet (meer) resolved

### ISSUE THREAD

**Issue by pvgenuchten** [dataoverheid/waardelijsten#1]
kijk bijvoorbeeld naar:

https://github.com/dataoverheid/waardelijsten/blob/496af4080150ff723e9fb3aedf08f4c384b9f502/v2.0.0/organisations.json#L3

https://github.com/dataoverheid/waardelijsten/blob/496af4080150ff723e9fb3aedf08f4c384b9f502/v2.0.0/organisations.json#L199

Een alternatieve aanpak zou zijn om een # te gebruiken om naar een onderdeel in een verzameld bestand te verwijzen, bv:

https://data.overheid.nl/service/waardelijsten/dcatapdonl_donl_organization#3TUDatacenter

**Comment by supportindicia** [comment]
Hi Paul, we hebben de redirects aangepast zodat /organisatie nu worden redirect naar /community/organization
Hiermee zou bovenstaande moeten zijn verholpen. We zullen issue hiermee sluiten.
